name: Upload to CurseForge
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  Zip-And-Upload-Addon-ZIP:  
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set version tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Echo version env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Create addon folder
        run: |
          mkdir FlightTimerClassic
          mv Data.lua FlightTimerClassic.lua FlightTimerClassic.toc ./FlightTimerClassic
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: FlightTimerClassic/
          dest: FlightTimerClassic-${{ env.RELEASE_VERSION }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: FlightTimerClassic
          path: ${{ github.workspace }}/FlightTimerClassic-${{ env.RELEASE_VERSION }}.zip
      - name: Echo Create new Version in CurseForge
        shell: bash
        run: 'echo curl -v -H "X-Api-Token: ${{ secrets.CURSEFORGE__TOKEN }}" -F "metadata={ ''changelog'': ''See GitHub'', ''gameVersions'': [8722], ''releaseType'': ''beta'' }" -F file=@${{ github.workspace }}/FlightTimerClassic-${{ env.RELEASE_VERSION }}.zip "https://wow.curseforge.com/api/projects/${{ secrets.CURSEFORGE__PROJECTID }}/upload-file"'
      - name: Create new Version in CurseForge
        shell: bash
        run: 'curl -v -H "X-Api-Token: ${{ secrets.CURSEFORGE__TOKEN }}" -F "metadata={ ''changelog'': ''See GitHub'', ''gameVersions'': [8722], ''releaseType'': ''beta'' }" -F file=@${{ github.workspace }}/FlightTimerClassic-${{ env.RELEASE_VERSION }}.zip "https://wow.curseforge.com/api/projects/${{ secrets.CURSEFORGE__PROJECTID }}/upload-file"' 
